# Default values for backend-svc-helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# fullnameOverride: ""
# nameOverride: ""

replicaCount: 1

image:
  repository: samay1993/backend-service
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 5001

ingress:
  enabled: false
  className: "nginx"
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: backend-svc.local
      paths:
        - path: /
          pathType: Prefix
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources:
  limits:
    cpu: 500m
    memory: 256Mi
  requests:
    cpu: 200m
    memory: 128Mi

livenessProbe:
  httpGet:
    path: /
    port: http
readinessProbe:
  httpGet:
    path: /
    port: http

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80

env:
  AWS_DEFAULT_REGION: "us-east-1"
  LOCALSTACK_URL: "http://192.168.64.1:4566"
  LOCALSTACK_HOST: "localstack"

secrets:
  AWS_ACCESS_KEY_ID: "test"  # Will be encrypted in a SealedSecret
  AWS_SECRET_ACCESS_KEY: "test"  # Will be encrypted in a SealedSecret