apiVersion: v1
kind: Secret
metadata:
  name: aws-secrets
type: Opaque
data:
  AWS_ACCESS_KEY_ID: {{ b64enc .Values.secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: {{ b64enc .Values.secrets.AWS_SECRET_ACCESS_KEY }}
