apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "backend-svc-helm.fullname" . }}
  labels:
    {{- include "backend-svc-helm.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "backend-svc-helm.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "backend-svc-helm.selectorLabels" . | nindent 8 }}
    spec:
      hostNetwork: false
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: {{ .Values.service.targetPort }}
        env:
        - name: AWS_DEFAULT_REGION
          value: {{ .Values.env.AWS_DEFAULT_REGION }}
        - name: LOCALSTACK_URL
          value: {{ .Values.env.LOCALSTACK_URL }}
        - name: LOCALSTACK_HOST
          value: {{ .Values.env.LOCALSTACK_HOST }}
        # Secrets are referred from the SealedSecret created separately
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: aws-secrets
              key: AWS_ACCESS_KEY_ID
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: aws-secrets
              key: AWS_SECRET_ACCESS_KEY
        # livenessProbe:
        #   {{- toYaml .Values.livenessProbe | nindent 12 }}
        # readinessProbe:
        #   {{- toYaml .Values.readinessProbe | nindent 12 }}
        resources:
          {{- toYaml .Values.resources | nindent 12 }}


